name: ch2020
channels:
  - conda-forge
  - defaults
dependencies:
  - Flask=1.1.1
  - python=3.7.3
  - pip=19.3.1
  - PyAudio=0.2.11
  - requests=2.22.0
  - redis=5.0.3
  - pip:
    - pyserial==3.4
    - google-cloud-storage==1.25.0
    - SpeechRecognition==3.8.1
    - PyAudio==0.2.11